name: Release new package version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'patch, minor or major version'
        required: true
        default: 'patch'

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Script
      uses: actions/github-script@v3.1.0
      with:
        result-encoding: string
        script: |
          if (!['patch', 'minor', 'major'].includes(${{ github.event.inputs.version }})) {
            core.setFailed('Provided version is not patch, minor or major')
          }
    - name: Check input version
      run: exit 1
    - name: Checkout source code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Setup Node.js
      uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867
      with:
        node-version: 14.x
    - name: Cache yarn dependencies
      uses: c-hive/gha-yarn-cache@f23816cdbc6d287b7982b4a08096db01a6329c12
    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive
    - name: Create release
      run: yarn release -- ${{ github.event.inputs.version }} --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to NPM Registry
      uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
        scope: '@breeffy' 
    - run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_BREEFFY_ORG_PUBLISH_TOKEN }}
    - name: Publish to GitHub Registry
      uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867
      with:
        node-version: 14.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@breeffy'
    - run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}